# Ensemble Learning

## Initial Imports

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,balanced_accuracy_score
from imblearn.ensemble import EasyEnsembleClassifier

## Read the CSV and Perform Basic Data Cleaning

In [4]:
# Load the data
file_path = Path('Resources/LoanStats_2019Q1.csv')
df = pd.read_csv(file_path)

# Preview the data
df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

## Split the Data into Training and Testing

In [5]:
# Create our features
x_cols = [i for i in df.columns if i not in ("loan_status")]
X = df[x_cols]
X = pd.get_dummies(X)
# Create our target
y = df[["loan_status"]]

In [6]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.177238,1.0,0.123879,0.876121,0.383161,0.616839,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.381873,0.0,0.329446,0.329446,0.486161,0.486161,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [7]:
# Check the balance of our target values
y.head()
y['loan_status'].value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [8]:
# Split the X and y into X_train, X_test, y_train, y_test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)
y_test.head()

      loan_status
64559    low_risk
4355     low_risk
25635    low_risk
735      low_risk
1088     low_risk

## Data Pre-Processing

Scale the training and testing data using the `StandardScaler` from `sklearn`. Remember that when scaling the data, you only scale the features data (`X_train` and `X_testing`).

In [9]:
def listNonNumericCols(df):
    columns_non_numeric = []
    for i, col in zip(df.dtypes, X_train):
        if (i!="float64"):
            #print(col) 
            columns_non_numeric.append(col)  
    return columns_non_numeric

columns_non_numeric = listNonNumericCols(X_train)

In [10]:
# Create the StandardScaler instance

# Fit the Standard Scaler with the training data
# When fitting scaling functions, only train on the training dataset

data_scaler = StandardScaler()
data_scaler.fit(X_train)

StandardScaler()

## Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Display the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier only, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [11]:
# Resample the training data with the BalancedRandomForestClassifier
rf_model = RandomForestClassifier(n_estimators=500, random_state=78)

X_train_scaled = data_scaler.transform(X_train)
X_test_scaled = data_scaler.transform(X_test)

rf_model = rf_model.fit(X_train_scaled, y_train)
predictions = rf_model.predict(X_test_scaled)
rf_model

RandomForestClassifier(n_estimators=500, random_state=78)

In [12]:
# Calculated the balanced accuracy score
balanced_accuracy_score(y_test, predictions)

0.6606274500324321

In [13]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, predictions)

# Calculating the accuracy score
acc_score = accuracy_score(y_test, predictions)
print (acc_score)

0.9959895379250218

In [14]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, predictions))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.74      0.32      1.00      0.45      0.57      0.30        87
   low_risk       1.00      1.00      0.32      1.00      0.57      0.34     17118

avg / total       1.00      1.00      0.33      1.00      0.57      0.34     17205

In [15]:
# List the features sorted in descending order by feature importance
importances = rf_model.feature_importances_ 
indices = np.argsort(importances)[::-1]
for f in range(X.shape[1]):
    print(f"{X.columns.values[indices[f]]}: ({importances[indices[f]]})")

total_rec_prncp: (0.07819262938969855)
last_pymnt_amnt: (0.07368880558441393)
total_rec_int: (0.06847952363183761)
total_pymnt: (0.06344669253640638)
total_pymnt_inv: (0.057590189816405804)
out_prncp: (0.02198082892632269)
installment: (0.02085520001757928)
out_prncp_inv: (0.020119698700127173)
mo_sin_old_rev_tl_op: (0.017257349372648428)
dti: (0.016884213942801943)
mo_sin_old_il_acct: (0.015433665813122928)
max_bal_bc: (0.014983781930449585)
bc_util: (0.01399543354915838)
loan_amnt: (0.013891557298537284)
annual_inc: (0.013852279461532337)
revol_bal: (0.013676873559119286)
bc_open_to_buy: (0.013391346757110116)
total_rec_late_fee: (0.013322355527414276)
total_bal_ex_mort: (0.013165882503800418)
tot_cur_bal: (0.013143517222527028)
avg_cur_bal: (0.013033071692742634)
total_il_high_credit_limit: (0.012756131661074603)
tot_hi_cred_lim: (0.01264358625130996)
total_bc_limit: (0.01233881188284263)
total_bal_il: (0.012200132808920747)
il_util: (0.012024613027878488)
total_rev_hi_lim: (0.011907343518179308)
int_rate: (0.011886027004917619)
all_util: (0.011822136269450806)
total_acc: (0.011371368537713816)
mths_since_rcnt_il: (0.011221616434330417)
num_il_tl: (0.01033443255642536)
mths_since_recent_bc: (0.010165216002028365)
mths_since_recent_inq: (0.009941902292019831)
mo_sin_rcnt_rev_tl_op: (0.00952887776620688)
num_rev_accts: (0.009524627323386433)
num_actv_rev_tl: (0.009483773973804756)
num_rev_tl_bal_gt_0: (0.00947804157909814)
num_sats: (0.009422577216288324)
issue_d_Mar-2019: (0.008963635413393144)
mo_sin_rcnt_tl: (0.008906243621752944)
open_acc: (0.008861616837028621)
acc_open_past_24mths: (0.008373982812882675)
num_bc_tl: (0.008363678438152023)
total_cu_tl: (0.008344971080788053)
pct_tl_nvr_dlq: (0.0079336689142396)
num_actv_bc_tl: (0.007928093085458422)
inq_last_12m: (0.0077955607832407205)
num_op_rev_tl: (0.007767936081586884)
open_rv_24m: (0.007181133396567408)
open_il_24m: (0.007021508521384278)
num_bc_sats: (0.00666882977717937)
percent_bc_gt_75: (0.006303245968610729)
inq_fi: (0.006192934592404031)
num_tl_op_past_12m: (0.006125565406767349)
open_act_il: (0.006104801990483357)
open_acc_6m: (0.005994933237245727)
issue_d_Jan-2019: (0.005900812867751823)
mort_acc: (0.005580462671340691)
inq_last_6mths: (0.0052195244536480416)
open_rv_12m: (0.004970667191035674)
next_pymnt_d_Apr-2019: (0.004530029260598713)
open_il_12m: (0.004288585770750611)
next_pymnt_d_May-2019: (0.003947277587515377)
issue_d_Feb-2019: (0.003939616651507425)
delinq_2yrs: (0.00390523307252194)
tot_coll_amt: (0.003752747351604565)
num_accts_ever_120_pd: (0.0036851330477343076)
pub_rec_bankruptcies: (0.002561051589453135)
pub_rec: (0.0023993507920877636)
verification_status_Source Verified: (0.002104569909084947)
verification_status_Verified: (0.0020706724328688826)
num_tl_90g_dpd_24m: (0.002030188233529941)
verification_status_Not Verified: (0.0019892360311542833)
home_ownership_MORTGAGE: (0.0018975302605332143)
home_ownership_OWN: (0.0018139450734606247)
application_type_Individual: (0.0017691097011731814)
application_type_Joint App: (0.001701426350474016)
home_ownership_RENT: (0.0016718364183609352)
initial_list_status_f: (0.001276281485260834)
initial_list_status_w: (0.001254126488834894)
collections_12_mths_ex_med: (0.0011573915424009534)
home_ownership_ANY: (0.0010192300500106736)
chargeoff_within_12_mths: (0.0002955104165047061)
num_tl_30dpd: (0.0)
tax_liens: (0.0)
delinq_amnt: (0.0)
num_tl_120dpd_2m: (0.0)
hardship_flag_N: (0.0)
collection_recovery_fee: (0.0)
pymnt_plan_n: (0.0)
acc_now_delinq: (0.0)
policy_code: (0.0)
recoveries: (0.0)
debt_settlement_flag_N: (0.0)

### Easy Ensemble Classifier

In [16]:
# Train the Classifier
model = EasyEnsembleClassifier(n_estimators=500)
model = model.fit(X_train_scaled, y_train)
predictions = model.predict(X_test_scaled)

In [20]:
# Calculated the balanced accuracy score
balanced_accuracy_score(y_test, predictions)

0.9268586001426207

In [18]:
# Display the confusion matrix
confusion_matrix(y_test, predictions)

array([[   79,     8],
       [  930, 16188]])

In [19]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, predictions))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.08      0.91      0.95      0.14      0.93      0.86        87
   low_risk       1.00      0.95      0.91      0.97      0.93      0.86     17118

avg / total       0.99      0.95      0.91      0.97      0.93      0.86     17205

### Final Questions

1. Which model had the best balanced accuracy score?

    Easy Ensemble Classifier

2. Which model had the best recall score?

    Random Forest Classifier

3. Which model had the best geometric mean score?

    Easy Ensemble Classifier

4. What are the top three features?  

    total_rec_prncp, last_pymnt_amnt, total_rec_int